class Mnemonic:
    ASSIGN = 'ASSIGN'
    ADD = 'ADD'
    SUBTRACT = 'SUB'
    MULTIPLY = 'MULT'
    NOT = 'NOT'
    AND = 'AND'
    EQUALS = 'EQ'
    LESS_THAN = 'LT'
    JUMP_FALSE = 'JPF'
    JUMP = 'JP'
    PRINT = 'PRINT'
    FAKE = 'FAKE'
    PUSH = 'PUSH'
    POP = 'POP'
    NOP = 'NOP'